---
- hosts: localhost
  connection: local
  tasks:
    - name: Publish to S3 bucket
      s3_sync:
        region: "us-east-1"
        bucket: www.joelguilarte.com
        file_root: ../dist/web
        file_change_strategy: checksum
        delete: yes
      delegate_to: localhost
