name: CI
on: [push]

jobs:
  build:
    name: Build web
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
