name: CI
on: [push]

jobs:
  build:
    name: Build web
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.8
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build -- --prod
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
  publish:
    name: Publish web artifacts
    runs-on: ubuntu-18.04
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Download web dist from build job
        uses: actions/download-artifact@v1
        with:
          name: dist
          path: $GITHUB_WORKSPACE/
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
      - shell: bash
        run: |
          pip install pipenv
          cd $GITHUB_WORKSPACE
          pipenv install
          echo `ls -la`
